### ISSUE TITLE
Incomprehensible text

### ISSUE THREAD

**Issue by paolosezart** [B3ND1X/air-script#1]
Raspbian OS
In the window of the Handshake Snooper Agent incomprehensible squares:
![27-09-2023 12_23_23](https://github.com/B3ND1X/air-script/assets/38177890/193b7d3d-d662-425b-b7eb-e2e2ce23906f)

**Comment by B3ND1X** [comment]
Hi, 
This seems to be a problem with Fluxion itself or possibly your system, not Air-Script. 

I would suggest either doing some research to fix this on your own, or create an issue on the correct GitHub repo: 

[Fluxion official repository](https://github.com/FluxionNetwork/fluxion)

I am not a contributor or a developer for the FluxionNetwork and I am unqualified to be offering support for a tool I did not make or contribute to. 

I will however provide some resources that might point you in the right direction for finding a possible solution to your problem. 

I would suggest the following: 

[FluxionNetwork FAQ](https://github.com/FluxionNetwork/fluxion/wiki/FAQ)

[FluxionNetwork Discord](https://discordapp.com/invite/G43gptk)

[FluxionNetwork Gitter](https://gitter.im/FluxionNetwork/Lobby)

I hope this helps.
